Repository import-js/eslint-plugin-import, pull requests merged in 2018-03, with the labels that each got.

#1039 #656: Fix crashes that caused when using object-rest properties in `namespace` rule
  src/rules/namespace.js
  tests/src/rules/namespace.js
Labels: bug

#1044 add-missing-env-variable-in-webpack-config
  resolvers/webpack/index.js
  resolvers/webpack/test/config.js
  resolvers/webpack/test/files/some/goofy/path/bar.js
  resolvers/webpack/test/files/webpack.function.config.js
Labels: bug, resolver

#1045 adds more examples to the import/extensions rule docs
  docs/rules/extensions.md
Labels: docs

#1048 [Docs] fixes problem with weird highlighting
  docs/rules/extensions.md
Labels: docs

#908 Add autofixer for order rule
  CHANGELOG.md
  docs/rules/order.md
  src/rules/order.js
  tests/src/rules/order.js
Labels: import/export ordering

#1028 Webpack -> webpack
  README.md
Labels: docs

#1046 add fixer for `first`
  docs/rules/first.md
  src/rules/first.js
  tests/src/rules/first.js
Labels: import/export ordering
