Repository import-js/eslint-plugin-import, pull requests merged in 2018-04, with the labels that each got.

#880 Add `allow-require` option to `no-commonjs` rule
  docs/rules/no-commonjs.md
  src/rules/no-commonjs.js
  tests/src/rules/no-commonjs.js
Labels: enhancement, semver-minor

#1068 Adds no-useless-path-segments documentation.
  CHANGELOG.md
  README.md
  docs/rules/no-useless-path-segments.md
Labels: docs

#1070 Dynamic import chunkname rule
  README.md
  docs/rules/dynamic-import-chunkname.md
  src/index.js
  src/rules/dynamic-import-chunkname.js
  tests/src/rules/dynamic-import-chunkname.js
Labels: accepted, rule proposal, semver-minor

#1057 Ignore type imports for named rule.
  CHANGELOG.md
  docs/rules/named.md
  src/rules/named.js
  tests/src/rules/named.js
Labels: flow

#1087 fix typo
  README.md
Labels: docs

#1088 Fix typo: 'runtime'
  tests/src/utils.js
Labels: docs
