Repository import-js/eslint-plugin-import, pull requests merged in 2019-12, with the labels that each got.

#1491 [core]: regex marking packages as internal
  CHANGELOG.md
  README.md
  docs/rules/order.md
  src/core/importType.js
  tests/src/core/importType.js
Labels: semver-minor

#1542 [flow] `no-unused-modules`: add flow type support
  CHANGELOG.md
  src/rules/no-unused-modules.js
  tests/files/no-unused-modules/flow-0.js
  tests/files/no-unused-modules/flow-1.js
  tests/files/no-unused-modules/flow-2.js
  tests/src/rules/no-unused-modules.js
Labels: flow

#1494 fix: import/no-cycle triggering errors for Flow imports
  CHANGELOG.md
  src/ExportMap.js
  tests/files/cycles/flow-types-depth-one.js
  tests/files/cycles/flow-types-depth-two.js
  tests/files/cycles/flow-types.js
  tests/src/rules/no-cycle.js
Labels: flow

#1386 `order` rule: add pathGroups option to add support to order by paths
  CHANGELOG.md
  docs/rules/order.md
  src/rules/order.js
  tests/src/rules/order.js
Labels: import/export ordering, semver-minor

#1108 no-duplicates: add a query-string option to handle false positives wh…
  CHANGELOG.md
  docs/rules/no-duplicates.md
  src/rules/no-duplicates.js
  tests/src/rules/no-duplicates.js
Labels: enhancement, semver-minor

#1503 feat: enable passing cwd as an option to webpack resolve
  resolvers/webpack/CHANGELOG.md
  resolvers/webpack/index.js
  resolvers/webpack/test/example.js
  resolvers/webpack/test/root.js
Labels: resolver

#1439 [no-commonjs] add allowConditionalRequire option
  CHANGELOG.md
  docs/rules/no-commonjs.md
  src/rules/no-commonjs.js
  tests/src/rules/no-commonjs.js
Labels: semver-minor

#1562 [import/order] Fix alphabetize bug with newlines-between
  src/rules/order.js
  tests/src/rules/order.js
Labels: import/export ordering

#1586 Enhancement alphabetize case insensitive
  CHANGELOG.md
  docs/rules/order.md
  src/rules/order.js
  tests/src/rules/order.js
Labels: semver-minor
