Repository import-js/eslint-plugin-import, pull requests merged in 2019-10, with the labels that each got.

#1401 Make no-namespace rule fixable
  CHANGELOG.md
  README.md
  docs/rules/no-namespace.md
  src/rules/no-namespace.js
  tests/src/rules/no-namespace.js
Labels: semver-minor

#1495 Fix ExportMap for a merged typescript namespace
  CHANGELOG.md
  src/ExportMap.js
  tests/files/typescript-export-assign-merged.d.ts
  tests/src/rules/named.js
Labels: typescript

#1499 Fix spelling of “TypeScript”
  .travis.yml
  CHANGELOG.md
  README.md
  src/rules/export.js
  tests/dep-time-travel.sh
  tests/src/rules/export.js
  tests/src/rules/named.js
  tests/src/rules/no-deprecated.js
  tests/src/rules/prefer-default-export.js
  utils/CHANGELOG.md
Labels: docs, typescript
