Repository import-js/eslint-plugin-import, pull requests merged in 2019-04, with the labels that each got.

#1312 no-duplicates: Add autofix
  CHANGELOG.md
  docs/rules/no-duplicates.md
  src/rules/no-duplicates.js
  tests/src/rules/no-duplicates.js
Labels: semver-minor

#1304 support export type named exports from typescript
  README.md
  package.json
  src/ExportMap.js
  tests/dep-time-travel.sh
  tests/src/core/getExports.js
  tests/src/rules/named.js
  tests/src/rules/order.js
  tests/src/utils.js
Labels: typescript

#1218 Fix overwriting of dynamic import() CallExpression
  src/rules/no-cycle.js
  tests/src/rules/no-cycle.js
  tests/src/rules/no-relative-parent-imports.js
  tests/src/rules/no-unresolved.js
  tests/src/rules/no-useless-path-segments.js
  utils/moduleVisitor.js
Labels: bug

#1319 fix: false positives for typescript type + value export
  package.json
  src/rules/export.js
  tests/src/rules/export.js
  tests/src/utils.js
Labels: typescript

#1112 doc(no-relative-parent-imports): rename title
  docs/rules/no-default-export.md
  docs/rules/no-deprecated.md
  docs/rules/no-named-export.md
  docs/rules/no-relative-parent-imports.md
  docs/rules/no-self-import.md
Labels: docs

#1345 [fix] `named`: ignore Flow import typeof and export type
  CHANGELOG.md
  docs/rules/named.md
  src/rules/named.js
  tests/src/rules/named.js
Labels: flow
