Repository import-js/eslint-plugin-import, pull requests merged in 2019-05, with the labels that each got.

#1354 Fix apparent corner case with `import/no-commonjs` rule
  src/rules/no-commonjs.js
  tests/src/rules/no-commonjs.js
Labels: bug

#1358 [Docs]: add missing `no-unused-modules` in README
  README.md
Labels: docs

#1352 Indicates usage, and that plugin defaults to no-op
  README.md
  docs/rules/no-unused-modules.md
Labels: docs

#1363 Issue #1258: Document `env` option for `eslint-import-resolver-webpack`
  resolvers/webpack/README.md
Labels: docs

#1356 Improve support for Typescript declare structures
  src/ExportMap.js
  tests/files/typescript-declare.d.ts
  tests/files/typescript-export-assign.d.ts
  tests/src/rules/named.js
  utils/unambiguous.js
Labels: typescript

#1370 Docs: no cycle, split code examples so file separation is obvious
  docs/rules/no-cycle.md
Labels: docs

#1371 [fix] `no-unused-modules`: handle ClassDeclaration
  src/rules/no-unused-modules.js
  tests/files/no-unused-modules/file-0.js
  tests/files/no-unused-modules/file-q.js
  tests/src/rules/no-unused-modules.js
Labels: bug
