Repository import-js/eslint-plugin-import, pull requests merged in 2019-06, with the labels that each got.

#1372 [New] `order`: add fixer for destructuring commonjs import
  src/rules/order.js
  tests/src/rules/order.js
Labels: semver-minor

#1375 Added support for correctly ordering unknown types e.g. custom aliases
  CHANGELOG.md
  docs/rules/order.md
  src/rules/order.js
  tests/src/rules/order.js
Labels: import/export ordering, semver-minor

#1389 Update no-named-as-default-member.md
  docs/rules/no-named-as-default-member.md
Labels: docs
