Repository import-js/eslint-plugin-import, pull requests merged in 2020-04, with the labels that each got.

#1707 [Fix] `group-exports`: Flow type export awareness
  CHANGELOG.md
  docs/rules/group-exports.md
  package.json
  src/rules/group-exports.js
  tests/src/rules/group-exports.js
Labels: bug, flow

#1724 Bug in order.js preventing from assigning `external` to patterns using `pathGroups`
  CHANGELOG.md
  src/rules/order.js
  tests/src/rules/order.js
Labels: bug

#1726 Disable import/named in the TypeScript configuration
  CHANGELOG.md
  config/typescript.js
Labels: typescript

#1676 [Fix] `no-duplicates`: Handle TS import type
  CHANGELOG.md
  package.json
  tests/src/rules/no-duplicates.js
Labels: typescript

#1528 [TypeScript] Support default exports in TSExportAssignment.
  CHANGELOG.md
  src/ExportMap.js
  tests/files/typescript-default.ts
  tests/files/typescript-export-assign-default-reexport.ts
  tests/files/typescript-export-assign-default.d.ts
  tests/files/typescript-export-assign-mixed.d.ts
  tests/files/typescript-export-assign-namespace-merged.d.ts
  tests/files/typescript-export-assign-namespace.d.ts
  tests/src/rules/default.js
  tests/src/rules/named.js
Labels: typescript

#1690 Remove duplicate no-unused-modules from docs
  CHANGELOG.md
  README.md
Labels: docs

#1705 [reolvers/webpack] [fix] provide config fallback
  resolvers/webpack/CHANGELOG.md
  resolvers/webpack/index.js
Labels: package: resolver/webpack
