Repository import-js/eslint-plugin-import, pull requests merged in 2020-02, with the labels that each got.

#1619 export: Handle function overloading in '*.d.ts'
  CHANGELOG.md
  src/rules/export.js
  tests/src/rules/export.js
Labels: typescript

#1626 [Fix] `order`: Fix alphabetize for mixed requires and imports
  CHANGELOG.md
  src/rules/order.js
  tests/src/rules/order.js
Labels: bug, import/export ordering

#1663 `resolvers/node`: [New] add `.node` extension
  resolvers/node/CHANGELOG.md
  resolvers/node/index.js
  resolvers/node/test/dot-node.node
  resolvers/node/test/native.node
  resolvers/node/test/paths.js
Labels: package: resolver/node, semver-minor
