Repository import-js/eslint-plugin-import, pull requests merged in 2021-05, with the labels that each got.

#1993 [Docs] Correcting peerDependencies option default to `true`
  CHANGELOG.md
  docs/rules/no-extraneous-dependencies.md
Labels: docs

#1997 [New] `no-unused-modules`: Support destructuring
  CHANGELOG.md
  src/rules/no-unused-modules.js
  tests/files/no-unused-modules/destructuring-a.js
  tests/files/no-unused-modules/destructuring-b.js
  tests/src/rules/no-unused-modules.js
Labels: semver-minor

#2021 [New] `order`: support type imports
  CHANGELOG.md
  docs/rules/order.md
  src/rules/order.js
  tests/src/rules/order.js
Labels: flow, import/export ordering, semver-minor, typescript

#2023 [resolvers/webpack] [New] add support for webpack 5 'externals function'
  resolvers/webpack/.eslintrc
  resolvers/webpack/CHANGELOG.md
  resolvers/webpack/index.js
  resolvers/webpack/test/externals.js
  resolvers/webpack/test/files/webpack.config.webpack5.async-externals.js
  resolvers/webpack/test/files/webpack.config.webpack5.js
Labels: package: resolver/webpack

#1992 [Docs] `order`: Document options required to match ordering example
  CHANGELOG.md
  docs/rules/order.md
Labels: docs, import/export ordering

#1990 [New] `order`: Add `warnOnUnassignedImports` option to enable warnings for out of order unassigned imports
  CHANGELOG.md
  docs/rules/order.md
  src/rules/order.js
  tests/src/rules/order.js
Labels: semver-minor

#2034 [Docs] Add import/recommended ruleset to README
  CHANGELOG.md
  README.md
Labels: docs

#2075 [Docs] Add no-relative-packages to list of to the list of rules
  CHANGELOG.md
  README.md
Labels: docs
