Repository import-js/eslint-plugin-import, pull requests merged in 2021-08, with the labels that each got.

#2160 Use getPhysicalFilename() instead of getFilename() if available (ESLint 7.28+)
  CHANGELOG.md
  src/core/packagePath.js
  src/rules/named.js
  src/rules/newline-after-import.js
  src/rules/no-cycle.js
  src/rules/no-extraneous-dependencies.js
  src/rules/no-import-module-exports.js
  src/rules/no-relative-packages.js
  src/rules/no-relative-parent-imports.js
  src/rules/no-restricted-paths.js
  src/rules/no-self-import.js
  src/rules/no-unassigned-import.js
  src/rules/no-unused-modules.js
  src/rules/no-useless-path-segments.js
  tests/src/core/getExports.js
  tests/src/core/resolve.js
  utils/resolve.js
Labels: package: utils

#2156 [Docs] `order`: improve the documentation for the `pathGroupsExcludedImportTypes` option
  CHANGELOG.md
  docs/rules/order.md
Labels: docs

#1223 [New] `no-dynamic-require`: add option `esmodule`
  CHANGELOG.md
  src/rules/no-dynamic-require.js
  tests/src/rules/no-dynamic-require.js
Labels: semver-minor

#1222 [New] `named`: add commonjs option
  CHANGELOG.md
  src/rules/named.js
  tests/src/rules/named.js
Labels: semver-minor

#2112 [New] `no-namespace`: Add `ignore` option
  CHANGELOG.md
  docs/rules/no-namespace.md
  src/rules/no-namespace.js
  tests/src/rules/no-namespace.js
Labels: semver-minor

#1847 [New] `max-dependencies`: add option `ignoreTypeImports`
  CHANGELOG.md
  src/rules/max-dependencies.js
  tests/src/rules/max-dependencies.js
Labels: semver-minor

#2179 [Docs] add description how to use plugin with pnp/yarn berry
  CHANGELOG.md
  README.md
Labels: docs

#2184 [Fix] ExportMap: Add default export when esModuleInterop is true and anything is exported
  CHANGELOG.md
  src/ExportMap.js
  tests/files/typescript-export-react-test-renderer/index.d.ts
  tests/files/typescript-export-react-test-renderer/tsconfig.json
  tests/src/rules/default.js
Labels: bug, typescript

#2140 [Docs] `extensions`: improved cases for using `@/...`
  CHANGELOG.md
  docs/rules/extensions.md
Labels: docs

#2196 Document `ignoreTypeImports` option for max-dependencies rule
  CHANGELOG.md
  docs/rules/max-dependencies.md
Labels: docs

#2149 [Fix] `no-duplicates`: type import fixer generates valid TypeScript
  CHANGELOG.md
  src/rules/no-duplicates.js
  tests/src/rules/no-duplicates.js
Labels: bug
