Repository import-js/eslint-plugin-import, pull requests merged in 2022-04, with the labels that each got.

#2399 [New] `newline-after-import`: add `considerComments` option
  CHANGELOG.md
  docs/rules/newline-after-import.md
  src/rules/newline-after-import.js
  tests/src/rules/newline-after-import.js
Labels: semver-minor

#2440 [docs] note use of typescript in readme `import/extensions` section
  CHANGELOG.md
  README.md
Labels: typescript, docs

#2392 [Docs] `order`: use correct default value
  CHANGELOG.md
  docs/rules/order.md
Labels: docs
