Repository import-js/eslint-plugin-import, pull requests merged in 2024-08, with the labels that each got.

#3039 [utils] [fix] `parse`: Also delete parserOptions.projectService
  utils/CHANGELOG.md
  utils/parse.js
Labels: typescript, package: utils

#2998 optimize no-cycle rule using strongly connected components
  CHANGELOG.md
  package.json
  src/rules/no-cycle.js
  src/scc.js
  tests/src/rules/no-cycle.js
  tests/src/scc.js
Labels: semver-minor

#3033 [Fix] `no-duplicates`: Removing duplicates breaks in TypeScript
  CHANGELOG.md
  src/rules/no-duplicates.js
  tests/src/rules/no-duplicates.js
Labels: typescript

#3036 [Docs] order: update the description of the `pathGroupsExcludedImportTypes` option
  CHANGELOG.md
  docs/rules/order.md
Labels: docs

#2885 [Fix] `order`: do not compare first path segment for relative paths
  CHANGELOG.md
  src/rules/order.js
  tests/src/rules/order.js
Labels: import/export ordering
