Repository import-js/eslint-plugin-import, pull requests merged in 2024-12, with the labels that each got.

#3024 [New] add `enforce-node-protocol-usage` rule
  .markdownlint.json
  CHANGELOG.md
  README.md
  docs/rules/enforce-node-protocol-usage.md
  src/index.js
  src/rules/enforce-node-protocol-usage.js
  tests/src/rules/enforce-node-protocol-usage.js
Labels: rule proposal, semver-minor

#3124 [utils] [fix] `unambiguous`: detect modules exported from minified code
  tests/files/minified/no-newline.js
  tests/files/minified/one-line-no-semi-renamed.js
  tests/files/minified/one-line-no-semi.js
  tests/files/minified/one-line.js
  tests/src/core/getExports.js
  utils/CHANGELOG.md
  utils/unambiguous.js
Labels: package: utils

#3126 [Docs] add flat config guide for using `tseslint.config()`
  CHANGELOG.md
  README.md
Labels: typescript, docs

#3122 [Docs] add missing comma
  CHANGELOG.md
  README.md
Labels: docs

#3105 [New] `extensions`: allow enforcement decision overrides based on specifier
  CHANGELOG.md
  src/rules/extensions.js
  tests/src/rules/extensions.js
Labels: semver-minor
