Repository import-js/eslint-plugin-import, pull requests merged in 2025-01, with the labels that each got.

#3138 [meta] Update flatConfig example to include typescript config
  CHANGELOG.md
  README.md
Labels: typescript, docs

#3115 [meta] issue template with guidance for bug reports
  .github/issue_template.md
Labels: docs

#3128 [Fix] `order`: ensure arcane imports do not cause undefined behavior
  CHANGELOG.md
  src/rules/order.js
  tests/src/rules/order.js
Labels: import/export ordering

#3129 [New] `order`: add `consolidateIslands` option to collapse excess spacing for aesthetically pleasing imports
  CHANGELOG.md
  docs/rules/order.md
  src/rules/order.js
  tests/src/rules/order.js
Labels: semver-minor
